### ISSUE TITLE
Change hardcoded program blocks list

### ISSUE THREAD

**Issue by stefaj** [stefan-j/blockly#1]
A canvas may only contain one block entry point defining the main.
Once a main block is added to the canvas another one may not be added from the toolbox.

This was implemented in flyout.js in commit 58a370fa6888b02b31dc9c967b4943b9010087e2. However the list of program blocks are currently hardcoded.

This logic should be moved.

**Comment by stefaj** [comment]
Maybe have a static main block?

**Comment by cdsmith** [comment]
A main block would be okay, if you add a type for `Program`.  But honestly, I prefer it the way it is now.
